---
- hosts: 172.31.18.207
  become: yes
  tasks:
   - name: I wan to execute linux command
     command: hostname -f
     register: mytaskres

   - name: I want to display through debug
     debug:
       msg: "{{mytaskres}}"

   - name: install git
     apt:
       name: git
       state: present
     when: mytaskres.stderr== ""

   - name: install tree
     apt:
       name: tree
       state: present
     when: mytaskres.stderr!= ""