---
- hosts: 172.31.18.207
  become: yes
  tasks:
  - include_tasks: myfile.yml 
  - name: copy static file into ansible nodes
    copy:
      src: mytestfile
      dest: /home/ubuntu/mystaticfile
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: adding dynamic files to ansible nodes
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: startwebserver
  
  - name: how to download internet files
    get_url:
      url: https://get.jenkins.io/war-stable/2.346.2/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes

  handlers:
  - name: startwebserver
    service:
       name: apache2
       state: started       